# Generated by Django 4.2.5 on 2023-09-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('task_description', models.TextField()),
                ('task_status', models.BooleanField(default=False)),
                ('task_creaated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
