# Generated by Django 4.2.5 on 2023-09-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task_creaated',
            new_name='task_created',
        ),
    ]
