# Generated by Django 4.2.5 on 2023-10-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
