# Generated by Django 4.2.5 on 2023-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
