# Generated by Django 4.2.5 on 2023-10-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0016_alter_todo_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_created',
        ),
    ]
