# Generated by Django 4.2.5 on 2023-10-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0017_remove_todo_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
