# Generated by Django 4.2.5 on 2023-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0018_alter_todo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(5, '⭐'), (4, '⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐⭐⭐'), (1, '⭐⭐⭐⭐⭐')], null=True),
        ),
    ]
