# Generated by Django 4.2.5 on 2023-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0019_alter_priority_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.IntegerField(choices=[(5, '⭐'), (4, '⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐⭐⭐'), (1, '⭐⭐⭐⭐⭐')], null=True),
        ),
    ]
